spring.datasource.url=jdbc:postgresql://localhost:5432/taskify
spring.datasource.username=taskify
spring.datasource.password=taskify

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true